name: deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          package-manager-cache: false
      - id: cache
        run: |
          set -euo pipefail
          dir="$(pnpm store path)"
          echo "dir=${dir}" >> "$GITHUB_OUTPUT"
      - id: cache-key
        run: |
          set -euo pipefail
          echo "value=${RUNNER_ENVIRONMENT}-${RUNNER_OS}-${RUNNER_ARCH}-${HASH_FILES}" >> "$GITHUB_OUTPUT"
        env:
          HASH_FILES: ${{ hashFiles('pnpm-lock.yaml') }}
      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.cache.outputs.dir }}
          key: ${{ steps.cache-key.outputs.value }}
      - run: pnpm install --frozen-lockfile --ignore-scripts --prefer-offline
      - run: pnpm run build
      - if: ${{ github.ref_name == 'main' }}
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.cache.outputs.dir }}
          key: ${{ steps.cache-key.outputs.value }}
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: dist
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      pages: write
      id-token: write
    needs:
      - build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
